version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: little-chat-app

volumes:
  dbdata: {}
